server:
  port: 8090

spring:
  application:
    name: rococo-gateway

logging:
  file:
    path: ./logs/rococo-gateway
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

grpc:
  client:
    grpcMuseumClient:
      address: "static://127.0.0.1:8095"
      enableKeepAlive: true
      negotiationType: plaintext
    grpcArtisClient:
      address: "static://127.0.0.1:8095"
      enableKeepAlive: true
      negotiationType: plaintext
    grpcPaintingClient:
      address: "static://127.0.0.1:8095"
      enableKeepAlive: true
      negotiationType: plaintext
    grpcGeoClient:
      address: "static://127.0.0.1:8095"
      enableKeepAlive: true
      negotiationType: plaintext



rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-gateway:
  base-uri: 'http://127.0.0.1:8090'
rococo-geo:
  base-uri: 'http://127.0.0.1:8093'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

grpc:
  client:
    grpcMuseumClient:
      address: "static://127.0.0.1:8095"
      enableKeepAlive: true
      negotiationType: plaintext
    grpcArtisClient:
      address: "static://127.0.0.1:8095"
      enableKeepAlive: true
      negotiationType: plaintext
    grpcPaintingClient:
      address: "static://127.0.0.1:8095"
      enableKeepAlive: true
      negotiationType: plaintext
    grpcGeoClient:
      address: "static://127.0.0.1:8095"
      enableKeepAlive: true
      negotiationType: plaintext


rococo-userdata:
  base-uri: 'http://userdata.rococo.dc:8089'
rococo-front:
  base-uri: 'http://frontend.rococo.dc'
rococo-gateway:
  base-uri: 'http://gateway.rococo.dc:8090'
---
