CREATE DATABASE IF NOT EXISTS `rococo-auth` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `rococo-logs` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `rococo` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;